tower-rate-limit/src/lib.rs, tower-timeout/src/lib.rs
I missed these crates in #51 because the `Error` impls were not required in Conduit, but for completeness sake,  I've added them as well.
=> Add Error impls to tower-rate-limit and tower-timeout as well

tower-balance/Cargo.toml, tower-balance/src/choose/mod.rs, tower-balance/src/lib.rs
indexmap is the new ordermap.
Signed-off-by: Brian Smith <brian@briansmith.org>
=> Replace ordermap dependency with indexmap.

tower-rate-limit/src/lib.rs
This should de-break the build. However, I'm concerned that this made it pass CI --- we should fix the Travis configs.
=> Fix missing comma in tower-rate-limit Error impl

tower-balance/Cargo.toml
Signed-off-by: Brian Smith <brian@briansmith.org>
=> Upgrade indexmap dependency to version 1.

Cargo.toml, tower-buffer/src/lib.rs, tower-mock/src/lib.rs, tower-retry/Cargo.toml, tower-retry/README.md, tower-retry/src/lib.rs, tower-retry/tests/retry.rs
Initial sketch of a `Retry` middleware, ref #14.
=> Tower Retry

tower-reconnect/src/lib.rs
This reduces some of the generics on the types, which was mostly just annoying and not needed.
While here, I also renamed `Error::Inner` to `Error::Service`, since I found `Inner` to be confusing.
=> refine generics on Reconnect types

tower-balance/examples/demo.rs, tower-buffer/Cargo.toml, tower-buffer/src/lib.rs, tower-buffer/tests/buffer.rs
=> Make Buffer::new use DefaultExecutor

tower-buffer/src/lib.rs
Previously, `tower_buffer::Worker` would continue to loop indefinitely, even if both the incoming request stream and the service returned `NotReady`, starving the reactor in the process.
=> Don't make buffer::Worker block the reactor

README.md
Fixes a few spelling mistakes in the README
=> Various small typos in README

tower-balance/examples/demo.rs, tower-buffer/src/error.rs, tower-buffer/src/future.rs, tower-buffer/src/lib.rs, tower-buffer/src/message.rs, tower-buffer/src/worker.rs, tower-buffer/tests/buffer.rs, tower-mock/src/lib.rs
=> buffer: replace generic error with Box<Error>

ci/azure-install-rust.yml, ci/azure-rustfmt.yml, ci/azure-test-stable.yml
Cargo is buggy when specifying the crate to run a command against.
=> ci: `cd` into crate instead of `-p $crate`

tower-buffer/tests/buffer.rs, tower-filter/tests/filter.rs, tower-in-flight-limit/tests/in_flight_limit.rs, tower-mock/Cargo.toml, tower-mock/src/error.rs, tower-mock/src/future.rs, tower-mock/src/lib.rs, tower-mock/tests/mock.rs, tower-rate-limit/tests/rate_limit.rs, tower-retry/tests/retry.rs
=> mock: Use Box<Error> instead of a generic

tower-reconnect/src/future.rs, tower-reconnect/src/lib.rs
=> Refresh Reconnect

tower-layer/src/util/identity.rs, tower-layer/src/util/mod.rs
=> layer: Add an identity layer

tower/Cargo.toml, tower/src/layer.rs, tower/src/lib.rs
=> Add missing `TimeoutLayer` to tower

tower-balance/Cargo.toml, tower-balance/examples/demo.rs
This simplifies the balance example using functionality that has recently landed.
=> balance: cleanup example

tower-balance/examples/demo.rs
A recently merged PR failed to track master.
=> Fix build.

tower/examples/client.rs, tower/examples/server.rs, tower/src/builder/mod.rs, tower/tests/builder.rs
=> Rename `ServiceBuilder` builder fns.

tower/Cargo.toml, tower/src/builder/mod.rs, tower/src/lib.rs
These two crates will need to be finished at a later time.
=> Remove balance and filter from tower

tower/Cargo.toml
Signed-off-by: Alex Leong <alex@buoyant.io>
=> Pin tower-hyper dep to a specific revision

tower-service/src/lib.rs
to be compliant with deprecation of `boxed()` and updated `tokio_timer`api
=> update doc examples

ci/azure-is-release.yml, ci/azure-test-stable.yml
=> ci: fix isRelease condition

azure-pipelines.yml, tower-hedge/tests/hedge.rs
Signed-off-by: Alex Leong <alex@buoyant.io>
=> Fix tower-hedge tests and add to CI

tower-balance/src/pool.rs
This is very useful to avoid spinning up a million database connections for example (like I just did).
=> Allow setting a maximum number of services in pool

README.md
=> Add a note about v0.3.x branch to the readme

Cargo.toml, tower-util/Cargo.toml, tower-util/src/lib.rs, tower-util/src/service_fn.rs, tower-util/tests/service_fn.rs
This small PR ports service_fn to `std::future`.
=> Update `service_fn` to `std::future::Future`

Cargo.toml, tower-load/CHANGELOG.md, tower-load/Cargo.toml, tower-load/src/constant.rs, tower-load/src/instrument.rs, tower-load/src/lib.rs, tower-load/src/peak_ewma.rs, tower-load/src/pending_requests.rs
Will rebase and mark as ready once #320 lands (which this depends on)
=> Update tower-load to std::future

Cargo.toml, tower-buffer/CHANGELOG.md, tower-buffer/Cargo.toml, tower-buffer/src/future.rs, tower-buffer/src/lib.rs, tower-buffer/src/service.rs, tower-buffer/src/worker.rs, tower-buffer/tests/buffer.rs
Will rebase and mark as ready once I finish the changes and #322 lands (which this depends on)
=> Update tower-buffer to std::future

Cargo.toml, tower-timeout/CHANGELOG.md, tower-timeout/Cargo.toml, tower-timeout/src/future.rs, tower-timeout/src/lib.rs
This bumps tower-timeout to 0.3.0-alpha.1
=> Update tower-timeout to std::future

tower-buffer/Cargo.toml, tower-discover/Cargo.toml, tower-limit/Cargo.toml, tower-load/Cargo.toml
Requested by @LucioFranco in https://github.com/tower-rs/tower/pull/328#discussion_r322416331
=> Use the same version of pin-project everywhere

Cargo.toml, tower-filter/CHANGELOG.md, tower-filter/Cargo.toml, tower-filter/src/future.rs, tower-filter/src/lib.rs, tower-filter/src/predicate.rs, tower-filter/tests/filter.rs
This bumps tower-filter to 0.3.0-alpha.1
=> Update tower-filter to std::future

Cargo.toml, tower-spawn-ready/CHANGELOG.md, tower-spawn-ready/Cargo.toml, tower-spawn-ready/src/future.rs, tower-spawn-ready/src/layer.rs, tower-spawn-ready/src/lib.rs, tower-spawn-ready/src/make.rs, tower-spawn-ready/src/service.rs, tower-spawn-ready/tests/spawn_ready.rs
Will rebase and mark as ready once #330 lands (which this depends on)
=> Update tower-spawn-ready to std::future

tower-spawn-ready/tests/spawn_ready.rs
In https://github.com/tower-rs/tower/pull/332/commits/fe4f602d72990a76de3095e43a467133a60b6aa3 we removed the generic executor parameter (`E`) from `SpawnReady`. This caused the tests to stop working, but this wasn't caught by CI because, well, CI isn't working.
This fixes that.
=> spawn-ready: fix tests after removal of E

tower-balance/Cargo.toml, tower-buffer/Cargo.toml, tower-discover/Cargo.toml, tower-filter/Cargo.toml, tower-layer/Cargo.toml, tower-limit/Cargo.toml, tower-load-shed/Cargo.toml, tower-load/Cargo.toml, tower-reconnect/Cargo.toml, tower-retry/Cargo.toml, tower-spawn-ready/Cargo.toml, tower-test/Cargo.toml, tower-timeout/Cargo.toml, tower-util/Cargo.toml, tower/Cargo.toml
=> Pin all the alpha based dependencies

azure-pipelines.yml
=> Add `v0.3.x` branch to run CI

tower-balance/Cargo.toml, tower-buffer/CHANGELOG.md, tower-buffer/Cargo.toml, tower-buffer/src/worker.rs, tower/CHANGELOG.md, tower/Cargo.toml
Since I messed up the last one!
=> Prepare `tower-buffer` 0.3.0-alpha.1b release

tower-service/src/lib.rs
now this example builds successfully
=> Fix tower-service docs

tower-balance/Cargo.toml, tower-balance/src/p2c/layer.rs, tower-balance/src/p2c/make.rs, tower-balance/src/p2c/service.rs
Initially done in https://github.com/tower-rs/tower/pull/303, but split out here for convenience.
=> balance: Update rand to 0.7

tower-hedge/Cargo.toml, tower-layer/Cargo.toml, tower/Cargo.toml
`cargo udeps` shows some unused/misplaced dependencies.
=> Cleanup unused dependencies

tower-balance/Cargo.toml, tower-buffer/Cargo.toml, tower-discover/Cargo.toml, tower-filter/Cargo.toml, tower-hedge/Cargo.toml, tower-limit/Cargo.toml, tower-load-shed/Cargo.toml, tower-load/Cargo.toml, tower-make/Cargo.toml, tower-ready-cache/Cargo.toml, tower-reconnect/Cargo.toml, tower-retry/Cargo.toml, tower-spawn-ready/Cargo.toml, tower-test/Cargo.toml, tower-timeout/Cargo.toml, tower-util/Cargo.toml, tower/Cargo.toml
Update crate to use released versions of tower-service, tower-make and tower-layer
=> remove service, make and layer path deps

tower-balance/Cargo.toml, tower-balance/tests/p2c.rs
The hope for this was to reproduce #415 (which it does not sadly), but
at least it adds a test for p2c!
=> balance: Add a stress test for p2c

tower/src/lib.rs, tower/src/reconnect/future.rs, tower/src/reconnect/mod.rs
=> reconnect: Rework to allow real reconnecting

tower-limit/CHANGELOG.md, tower-limit/Cargo.toml, tower-limit/src/lib.rs
=> limit: Prepare `0.1.2` release

tower/src/limit/rate/service.rs, tower/tests/limit/rate.rs
Same as #438 but for the master branch.
=> rate: Fix rate limit not resetting

.github/workflows/CI.yml
=> Upgrade cargo deny action

README.md
=> Clean up readme and update status

tower-limit/CHANGELOG.md, tower-limit/Cargo.toml, tower-limit/src/lib.rs
=> limit: Prepare `v0.1.3` release

tower/CHANGELOG.md, tower/src/builder/mod.rs, tower/tests/builder.rs
=> Make `ServiceBuilder::service` take `self` by reference

tower-test/CHANGELOG.md, tower-test/Cargo.toml, tower-test/src/lib.rs
=> test: update tower-test to v0.4

tower-layer/CHANGELOG.md, tower-layer/Cargo.toml, tower-layer/src/lib.rs
=> layer: prepare to release v0.3.1

tower/src/macros.rs
=> tower: fix unused macros warning

tower/CHANGELOG.md, tower/Cargo.toml
Fixes https://github.com/tower-rs/tower/issues/530
=> Add "full" feature that turns on all other features

tower/CHANGELOG.md, tower/Cargo.toml
Fixes https://github.com/tower-rs/tower/issues/549
Tested with `cargo hack check --each-feature --no-dev-deps`
=> Only pull in tracing when necessary

tower-layer/src/layer_fn.rs, tower/CHANGELOG.md, tower/src/util/and_then.rs, tower/src/util/map_err.rs, tower/src/util/map_request.rs, tower/src/util/map_response.rs, tower/src/util/map_result.rs, tower/src/util/service_fn.rs, tower/src/util/then.rs
Fixes https://github.com/tower-rs/tower/issues/545
=> Make combinators implement `Debug` in more cases

.netlify.toml
Not sure this thing works, let's see.
=> chore: create doc preview website with Netlify

.github/workflows/CI.yml, deny.toml
=> Reenable bans check

tower/src/util/call_all/common.rs, tower/src/util/call_all/ordered.rs, tower/src/util/call_all/unordered.rs, tower/src/util/mod.rs
This change was missing from #649.
=> Unecessary bound in ServiceExt::call_all

tower/src/ready_cache/cache.rs
This replaces the use of `tokio::sync::Notify` with
`futures::task::AtomicWaker`. `Notify` requires the `Notified` future to
be held in order to remain interested in the notification. Dropping the
future returned by `Notify::notified` cancels interest in the
notification. So, the current code using `Notify` is incorrect, as the
`Notified` future is created on each poll and then immediately dropped,
releasing interest in the wakeup.
We could solve this by storing the `Notify::notified` future in the
`Pending` future, but this would be a bit of a pain, as the `Notified`
future borrows the `Notify`. I thought that it was a nicer alternative
to just rewrite this code to use `AtomicWaker` instead.
Also, `AtomicWaker` is a much simpler, lower-level primitive. It simply
stores a single waker …
=> ready_cache: use `futures::task::AtomicWaker` for cancelation

tower/README.md, tower/src/lib.rs
https://github.com/silvanshade/lspower
=> Remove `lspower` due to deprecation

tower/src/builder/mod.rs, tower/src/lib.rs, tower/src/limit/concurrency/service.rs, tower/src/limit/rate/service.rs, tower/src/load/constant.rs, tower/src/load/peak_ewma.rs, tower/src/util/mod.rs
… so extra doc(cfg) attributes aren't needed in most places.
=> chore: Use doc_auto_cfg

guides/building-a-middleware-from-scratch.md
Updating generic to be consistent with the rest of the examples
=> Updating generic to be consistent

guides/building-a-middleware-from-scratch.md
=> [typo] self.duration > self.timeout

tower/README.md
I forgot to migrate the link over.
=> Fix axum readme link

tower/src/filter/layer.rs
=> Derive `Clone` for `AsyncFilterLayer`

tower/src/balance/p2c/service.rs
=> chore: remove useless code

tower/src/retry/backoff.rs, tower/src/retry/budget/tps_budget.rs, tower/src/util/rng.rs, tower/tests/ready_cache/main.rs
=> docs:Fix some spelling mistakes

tower/Cargo.toml
Tackling https://github.com/tower-rs/tower/issues/784
Making sure users do not run into issues when trying tower.
=> Bump dependency on tower-layer

.github/workflows/CI.yml, Cargo.toml, tower/Cargo.toml
These dependencies seem not to be used.
=> chore: Remove unused dependency
